# Basic
title: nanhuayu
subtitle: 淡泊宁静 自强不息
welcome_message: <a href="https://github.com/nanhuayu" target="_blank">见字如面</a>
description: 我与世界相遇,<br>我自与世界相蚀,<br>我自不辱使命,<br>使我与众生相聚!
creator: <a href="http://nanhuayu.com">@nanhuayu</a>

url: "http://www.nanhuayu.com"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/nanhuayu/'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: nanhuayu
    github: nanhuayu
    twitter: nanhuayu
    gplus: 107108267983477358170
    mail: nanhuayu@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host

theme: jekyll-theme-cayman
